spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true