spring:
  datasource:
    url: jdbc:postgresql://nilknow.com:5432/postgres?currentSchema=public
    username: postgres
    password: jump666!
    hikari:
      maximum-pool-size: 4
      max-lifetime: 60000
      connection-timeout: 30000
      idle-timeout: 60000
  data:
    rest:
      base-path: /api
      defaultPageSize: 20
